version: '3.3'

services:

  # # # # Nextcloud start
  nextcloud_db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${NC_MYSQL_DATABASE}
      MYSQL_USER: ${NC_MYSQL_USER}
      MYSQL_PASSWORD: ${NC_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${NC_MYSQL_ROOT_PASSWORD}

  nextcloud_redis:
    image: redis:alpine
    restart: unless-stopped

  nextcloud_app:
    build: ./nextcloud_app
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud_db
      - REDIS_HOST=nextcloud_redis
    depends_on:
      - nextcloud_db
      - nextcloud_redis

  nextcloud_web:
    build: ./nextcloud_web
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_HOST: ${NC_URL}
      LETSENCRYPT_HOST: ${NC_URL}
    depends_on:
      - nextcloud_app

  nextcloud_cron:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud_db
      - nextcloud_redis

  nextcloud_letsencrypt_companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - proxy_certs:/etc/nginx/certs
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx_proxy
  # Nextcloud end # # #

  # # # # Wordpress start
  wordpress_db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${WP_MYSQL_DATABASE}
      MYSQL_USER: ${WP_MYSQL_USER}
      MYSQL_PASSWORD: ${WP_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WP_MYSQL_ROOT_PASSWORD}

  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    depends_on:
      - wordpress_db
    volumes:
       - wordpress:/var/www/html
       - wordpress_db:/var/lib/mysql
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_HOST: ${WP_URL}
      LETSENCRYPT_HOST: ${WP_URL}
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: ${WP_MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${WP_MYSQL_PASSWORD}
  # Wordpress end # # #

  # # # # Gitlab start
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: ${GL_URL}
    restart: unless-stopped
    ports:
    - target: 22
      published: 39904 # PUBLIC_SSH_PORT, can't be a string from .env
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "registry['log_level'] = 'warn'" # @FIXME
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_HOST: ${GL_URL}
      LETSENCRYPT_HOST: ${GL_URL}

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  # Gitlab end # # #

  # # # # Proxy-Webserver start
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: unless-stopped
    depends_on:
      - nginx_proxy
    environment:
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - proxy_conf:/etc/nginx/conf.d
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
      - proxy_dhparam:/etc/nginx/dhparam
      - proxy_certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx_proxy:
    build: ./nginx_proxy
    restart: unless-stopped
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - proxy_certs:/etc/nginx/certs:ro
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  # Proxy-Webserver end # # #

volumes:
  proxy_conf:
  proxy_vhost:
  proxy_html:
  proxy_dhparam:
  proxy_certs:
  wordpress:
  wordpress_db:
  nextcloud:
  nextcloud_db:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
